#pragma once
class AccountHelpLayer;
class AccountLayer;
class AccountLoginLayer;
class AccountRegisterLayer;
class AchievementBar;
class AchievementCell;
class AchievementManager;
class AchievementNotifier;
class AchievementsLayer;
class AdToolbox;
class AnimatedGameObject;
class AnimatedSpriteDelegate;
class AppDelegate;
class AudioEffectsLayer;
class BitmapFontCache;
class BonusDropdown;
class BoomListLayer;
class BoomListView;
class BoomScrollLayer;
class BoomScrollLayerDelegate;
class ButtonPage;
class ButtonSprite;
class CCAlertCircle;
class CCAnimatedSprite;
class CCAnimateFrameCache;
class CCBlockLayer;
class CCCircleAlert;
class CCCircleWave;
class CCCircleWaveDelegate;
class CCContentLayer;
class CCCountdown;
class CCCounterLabel;
class CCExtenderNode;
class CCIndexPath;
class CCLightFlash;
class CCLightStrip;
class CCMenuItemSpriteExtra;
class CCMenuItemToggler;
class CCMoveCNode;
class CCPartAnimSprite;
class CCScrollLayerExt;
class CCScrollLayerExtDelegate;
class CCSpritePart;
class CCSpritePlus;
class CCTextInputNode;
class CheckpointObject;
class ColorAction;
class ColorActionSprite;
class ColorChannelSprite;
class ColoredSection;
class ColorSelectDelegate;
class ColorSelectPopup;
class ColorSetupDelegate;
class CommentCell;
class CommentUploadDelegate;
class ConfigureHSVWidget;
class CreateGuidelinesLayer;
class CreateMenuItem;
class CreatorLayer;
class CustomizeObjectLayer;
class CustomListView;
class CustomSongCell;
class CustomSongDelegate;
class CustomSongLayer;
class CustomSongLayerDelegate;
class CustomSongWidget;
class DownloadMessageDelegate;
class DrawGridLayer;
class DynamicScrollDelegate;
class EditButtonBar;
class EditLevelLayer;
class EditorOptionsLayer;
class EditorPauseLayer;
class EditorUI;
class EditTriggersPopup;
class EffectGameObject;
class EndLevelLayer;
class EndPortalObject;
class EveryplayToolbox;
class ExtendedLayer;
class FileOperation;
class FileSaveManager;
class FLAlertLayer;
class FLAlertLayerProtocol;
class FMODAudioEngine;
class FMODSound;
class FontObject;
class frameValues;
class FRequestProfilePage;
class FriendRequestDelegate;
class FriendRequestPopup;
class FriendsProfilePage;
class GameCell;
class GameEffectsManager;
class GameLevelManager;
class GameManager;
class GameObject;
class GameObjectCopy;
class GameRateDelegate;
class GameSoundManager;
class GameStatsManager;
class GameStoreManager;
class GameToolbox;
class GaragePage;
class GhostTrailEffect;
class GJAccountBackupDelegate;
class GJAccountDelegate;
class GJAccountLoginDelegate;
class GJAccountManager;
class GJAccountRegisterDelegate;
class GJAccountSettingsDelegate;
class GJAccountSettingsLayer;
class GJAccountSyncDelegate;
class GJBaseGameLayer;
class GJColorSetupLayer;
class GJComment;
class GJCommentListLayer;
class GJDropDownLayer;
class GJDropDownLayerDelegate;
class GJEffectManager;
class GJFlyGroundLayer;
class GJFriendRequest;
class GJGameLevel;
class GJGarageLayer;
class GJGroundLayer;
class GJHttpResult;
class GJListLayer;
class GJMapPack;
class GJMessageCell;
class GJMessagePopup;
class GJMoreGamesLayer;
class GJMoveCommandLayer;
class GJObjectDecoder;
class GJOptionsLayer;
class GJRequestCell;
class GJRobotSprite;
class GJRotationControl;
class GJRotationControlDelegate;
class GJScaleControl;
class GJScaleControlDelegate;
class GJScoreCell;
class GJSearchObject;
class GJSongBrowser;
class GJSpecialColorSelect;
class GJSpecialColorSelectDelegate;
class GJSpriteColor;
class GJUserCell;
class GJUserMessage;
class GJUserScore;
class GJWriteMessagePopup;
class GManager;
class GooglePlayDelegate;
class GooglePlayManager;
class GravityEffectSprite;
class GroupCommandObject;
class HardStreak;
class HSVWidgetPopup;
class HSVWidgetPopupDelegate;
class InfoAlertButton;
class InfoLayer;
class InheritanceNode;
class KeybindingsLayer;
class KeybindingsManager;
class LeaderboardManagerDelegate;
class LeaderboardsLayer;
class LevelBrowserLayer;
class LevelCell;
class LevelCommentDelegate;
class LevelDeleteDelegate;
class LevelDownloadDelegate;
class LevelEditorLayer;
class LevelFeatureLayer;
class LevelInfoLayer;
class LevelManagerDelegate;
class LevelPage;
class LevelSearchLayer;
class LevelSelectLayer;
class LevelSettingsDelegate;
class LevelSettingsLayer;
class LevelSettingsObject;
class LevelTools;
class LevelUpdateDelegate;
class LevelUploadDelegate;
class LikeItemDelegate;
class LikeItemLayer;
class ListButtonBar;
class ListButtonBarDelegate;
class ListButtonPage;
class ListCell;
class LoadingCircle;
class LoadingLayer;
class LocalLevelManager;
class MapPackCell;
class MenuGameLayer;
class MenuLayer;
class MessageListDelegate;
class MessagesProfilePage;
class MoreOptionsLayer;
class MoreSearchLayer;
class MoreVideoOptionsLayer;
class MultilineBitmapFont;
class MusicDelegateHandler;
class MusicDownloadDelegate;
class MusicDownloadManager;
class MyLevelsLayer;
class NodePoint;
class NumberInputDelegate;
class NumberInputLayer;
class OBB2D;
class ObjectManager;
class ObjectToolbox;
class OpacityEffectAction;
class OptionsLayer;
class PauseLayer;
class PlatformDownloadDelegate;
class PlatformToolbox;
class PlayerCheckpoint;
class PlayerObject;
class PlayLayer;
class PointNode;
class PriceLabel;
class ProfilePage;
class PromoInterstitial;
class PulseEffectAction;
class RateLevelDelegate;
class RateLevelLayer;
class RateStarsLayer;
class RetryLevelLayer;
class RingObject;
class SavedLevelsLayer;
class ScrollingLayer;
class SearchButton;
class SecretLayer;
class SelectArtDelegate;
class SelectArtLayer;
class SelectFontLayer;
class SetGroupIDLayer;
class SetIDLayer;
class SetupObjectTogglePopup;
class SetupOpacityPopup;
class SetupPulsePopup;
class SetupSpawnPopup;
class sha1;
class ShareCommentLayer;
class ShareLevelLayer;
class ShareLevelSettingsLayer;
class SimpleObject;
class SimplePlayer;
class SlideInLayer;
class Slider;
class SliderThumb;
class SliderTouchLogic;
class SongCell;
class SongInfoLayer;
class SongInfoObject;
class SongObject;
class SongOptionsLayer;
class SongsLayer;
class SpawnTriggerAction;
class SpawnTriggerDelegate;
class SpeedObject;
class Spinor;
class SpriteAnimationManager;
class SpriteDescription;
class StartPosObject;
class StatsCell;
class StatsLayer;
class StatsObject;
class StoreToolbox;
class SupportLayer;
class TableView;
class TableViewCell;
class TableViewDataSource;
class TableViewDelegate;
class TeleportPortalObject;
class TextArea;
class TextInputDelegate;
class TriggerEffectDelegate;
class TutorialLayer;
class TutorialPopup;
class UILayer;
class UndoObject;
class UpdateAccountSettingsPopup;
class UploadActionDelegate;
class UploadActionPopup;
class UploadMessageDelegate;
class UploadPopup;
class UploadPopupDelegate;
class UserInfoDelegate;
class UserListDelegate;
class VideoOptionsLayer;
class GameObjectClass;
class GhostTrailDelegate;
class GJFriendStatus;
class PremiumPopup;
class SlideInLayerDelegate;

struct TodoReturnPlaceholder {
private:
    TodoReturnPlaceholder() = default;
    TodoReturnPlaceholder(TodoReturnPlaceholder const&) = default;
    TodoReturnPlaceholder(TodoReturnPlaceholder&&) = default;
    ~TodoReturnPlaceholder() = default;
public:
    friend class AccountHelpLayer;
    friend class AccountLayer;
    friend class AccountLoginLayer;
    friend class AccountRegisterLayer;
    friend class AchievementBar;
    friend class AchievementCell;
    friend class AchievementManager;
    friend class AchievementNotifier;
    friend class AchievementsLayer;
    friend class AdToolbox;
    friend class AnimatedGameObject;
    friend class AnimatedSpriteDelegate;
    friend class AppDelegate;
    friend class AudioEffectsLayer;
    friend class BitmapFontCache;
    friend class BonusDropdown;
    friend class BoomListLayer;
    friend class BoomListView;
    friend class BoomScrollLayer;
    friend class BoomScrollLayerDelegate;
    friend class ButtonPage;
    friend class ButtonSprite;
    friend class CCAlertCircle;
    friend class CCAnimatedSprite;
    friend class CCAnimateFrameCache;
    friend class CCBlockLayer;
    friend class CCCircleAlert;
    friend class CCCircleWave;
    friend class CCCircleWaveDelegate;
    friend class CCContentLayer;
    friend class CCCountdown;
    friend class CCCounterLabel;
    friend class CCExtenderNode;
    friend class CCIndexPath;
    friend class CCLightFlash;
    friend class CCLightStrip;
    friend class CCMenuItemSpriteExtra;
    friend class CCMenuItemToggler;
    friend class CCMoveCNode;
    friend class CCPartAnimSprite;
    friend class CCScrollLayerExt;
    friend class CCScrollLayerExtDelegate;
    friend class CCSpritePart;
    friend class CCSpritePlus;
    friend class CCTextInputNode;
    friend class CheckpointObject;
    friend class ColorAction;
    friend class ColorActionSprite;
    friend class ColorChannelSprite;
    friend class ColoredSection;
    friend class ColorSelectDelegate;
    friend class ColorSelectPopup;
    friend class ColorSetupDelegate;
    friend class CommentCell;
    friend class CommentUploadDelegate;
    friend class ConfigureHSVWidget;
    friend class CreateGuidelinesLayer;
    friend class CreateMenuItem;
    friend class CreatorLayer;
    friend class CustomizeObjectLayer;
    friend class CustomListView;
    friend class CustomSongCell;
    friend class CustomSongDelegate;
    friend class CustomSongLayer;
    friend class CustomSongLayerDelegate;
    friend class CustomSongWidget;
    friend class DownloadMessageDelegate;
    friend class DrawGridLayer;
    friend class DynamicScrollDelegate;
    friend class EditButtonBar;
    friend class EditLevelLayer;
    friend class EditorOptionsLayer;
    friend class EditorPauseLayer;
    friend class EditorUI;
    friend class EditTriggersPopup;
    friend class EffectGameObject;
    friend class EndLevelLayer;
    friend class EndPortalObject;
    friend class EveryplayToolbox;
    friend class ExtendedLayer;
    friend class FileOperation;
    friend class FileSaveManager;
    friend class FLAlertLayer;
    friend class FLAlertLayerProtocol;
    friend class FMODAudioEngine;
    friend class FMODSound;
    friend class FontObject;
    friend class frameValues;
    friend class FRequestProfilePage;
    friend class FriendRequestDelegate;
    friend class FriendRequestPopup;
    friend class FriendsProfilePage;
    friend class GameCell;
    friend class GameEffectsManager;
    friend class GameLevelManager;
    friend class GameManager;
    friend class GameObject;
    friend class GameObjectCopy;
    friend class GameRateDelegate;
    friend class GameSoundManager;
    friend class GameStatsManager;
    friend class GameStoreManager;
    friend class GameToolbox;
    friend class GaragePage;
    friend class GhostTrailEffect;
    friend class GJAccountBackupDelegate;
    friend class GJAccountDelegate;
    friend class GJAccountLoginDelegate;
    friend class GJAccountManager;
    friend class GJAccountRegisterDelegate;
    friend class GJAccountSettingsDelegate;
    friend class GJAccountSettingsLayer;
    friend class GJAccountSyncDelegate;
    friend class GJBaseGameLayer;
    friend class GJColorSetupLayer;
    friend class GJComment;
    friend class GJCommentListLayer;
    friend class GJDropDownLayer;
    friend class GJDropDownLayerDelegate;
    friend class GJEffectManager;
    friend class GJFlyGroundLayer;
    friend class GJFriendRequest;
    friend class GJGameLevel;
    friend class GJGarageLayer;
    friend class GJGroundLayer;
    friend class GJHttpResult;
    friend class GJListLayer;
    friend class GJMapPack;
    friend class GJMessageCell;
    friend class GJMessagePopup;
    friend class GJMoreGamesLayer;
    friend class GJMoveCommandLayer;
    friend class GJObjectDecoder;
    friend class GJOptionsLayer;
    friend class GJRequestCell;
    friend class GJRobotSprite;
    friend class GJRotationControl;
    friend class GJRotationControlDelegate;
    friend class GJScaleControl;
    friend class GJScaleControlDelegate;
    friend class GJScoreCell;
    friend class GJSearchObject;
    friend class GJSongBrowser;
    friend class GJSpecialColorSelect;
    friend class GJSpecialColorSelectDelegate;
    friend class GJSpriteColor;
    friend class GJUserCell;
    friend class GJUserMessage;
    friend class GJUserScore;
    friend class GJWriteMessagePopup;
    friend class GManager;
    friend class GooglePlayDelegate;
    friend class GooglePlayManager;
    friend class GravityEffectSprite;
    friend class GroupCommandObject;
    friend class HardStreak;
    friend class HSVWidgetPopup;
    friend class HSVWidgetPopupDelegate;
    friend class InfoAlertButton;
    friend class InfoLayer;
    friend class InheritanceNode;
    friend class KeybindingsLayer;
    friend class KeybindingsManager;
    friend class LeaderboardManagerDelegate;
    friend class LeaderboardsLayer;
    friend class LevelBrowserLayer;
    friend class LevelCell;
    friend class LevelCommentDelegate;
    friend class LevelDeleteDelegate;
    friend class LevelDownloadDelegate;
    friend class LevelEditorLayer;
    friend class LevelFeatureLayer;
    friend class LevelInfoLayer;
    friend class LevelManagerDelegate;
    friend class LevelPage;
    friend class LevelSearchLayer;
    friend class LevelSelectLayer;
    friend class LevelSettingsDelegate;
    friend class LevelSettingsLayer;
    friend class LevelSettingsObject;
    friend class LevelTools;
    friend class LevelUpdateDelegate;
    friend class LevelUploadDelegate;
    friend class LikeItemDelegate;
    friend class LikeItemLayer;
    friend class ListButtonBar;
    friend class ListButtonBarDelegate;
    friend class ListButtonPage;
    friend class ListCell;
    friend class LoadingCircle;
    friend class LoadingLayer;
    friend class LocalLevelManager;
    friend class MapPackCell;
    friend class MenuGameLayer;
    friend class MenuLayer;
    friend class MessageListDelegate;
    friend class MessagesProfilePage;
    friend class MoreOptionsLayer;
    friend class MoreSearchLayer;
    friend class MoreVideoOptionsLayer;
    friend class MultilineBitmapFont;
    friend class MusicDelegateHandler;
    friend class MusicDownloadDelegate;
    friend class MusicDownloadManager;
    friend class MyLevelsLayer;
    friend class NodePoint;
    friend class NumberInputDelegate;
    friend class NumberInputLayer;
    friend class OBB2D;
    friend class ObjectManager;
    friend class ObjectToolbox;
    friend class OpacityEffectAction;
    friend class OptionsLayer;
    friend class PauseLayer;
    friend class PlatformDownloadDelegate;
    friend class PlatformToolbox;
    friend class PlayerCheckpoint;
    friend class PlayerObject;
    friend class PlayLayer;
    friend class PointNode;
    friend class PriceLabel;
    friend class ProfilePage;
    friend class PromoInterstitial;
    friend class PulseEffectAction;
    friend class RateLevelDelegate;
    friend class RateLevelLayer;
    friend class RateStarsLayer;
    friend class RetryLevelLayer;
    friend class RingObject;
    friend class SavedLevelsLayer;
    friend class ScrollingLayer;
    friend class SearchButton;
    friend class SecretLayer;
    friend class SelectArtDelegate;
    friend class SelectArtLayer;
    friend class SelectFontLayer;
    friend class SetGroupIDLayer;
    friend class SetIDLayer;
    friend class SetupObjectTogglePopup;
    friend class SetupOpacityPopup;
    friend class SetupPulsePopup;
    friend class SetupSpawnPopup;
    friend class sha1;
    friend class ShareCommentLayer;
    friend class ShareLevelLayer;
    friend class ShareLevelSettingsLayer;
    friend class SimpleObject;
    friend class SimplePlayer;
    friend class SlideInLayer;
    friend class Slider;
    friend class SliderThumb;
    friend class SliderTouchLogic;
    friend class SongCell;
    friend class SongInfoLayer;
    friend class SongInfoObject;
    friend class SongObject;
    friend class SongOptionsLayer;
    friend class SongsLayer;
    friend class SpawnTriggerAction;
    friend class SpawnTriggerDelegate;
    friend class SpeedObject;
    friend class Spinor;
    friend class SpriteAnimationManager;
    friend class SpriteDescription;
    friend class StartPosObject;
    friend class StatsCell;
    friend class StatsLayer;
    friend class StatsObject;
    friend class StoreToolbox;
    friend class SupportLayer;
    friend class TableView;
    friend class TableViewCell;
    friend class TableViewDataSource;
    friend class TableViewDelegate;
    friend class TeleportPortalObject;
    friend class TextArea;
    friend class TextInputDelegate;
    friend class TriggerEffectDelegate;
    friend class TutorialLayer;
    friend class TutorialPopup;
    friend class UILayer;
    friend class UndoObject;
    friend class UpdateAccountSettingsPopup;
    friend class UploadActionDelegate;
    friend class UploadActionPopup;
    friend class UploadMessageDelegate;
    friend class UploadPopup;
    friend class UploadPopupDelegate;
    friend class UserInfoDelegate;
    friend class UserListDelegate;
    friend class VideoOptionsLayer;
    friend class GameObjectClass;
    friend class GhostTrailDelegate;
    friend class GJFriendStatus;
    friend class PremiumPopup;
    friend class SlideInLayerDelegate;

};
